export const PATCHY_VERSION_ENV_VAR = "PATCHY_VERSION";

export const PATCHY_REPO_URL_ENV_VAR = "PATCHY_REPO_URL";
export const PATCHY_REPO_DIR_ENV_VAR = "PATCHY_REPO_DIR";
export const PATCHY_REPO_BASE_DIR_ENV_VAR = "PATCHY_REPO_BASE_DIR";
export const PATCHY_PATCHES_DIR_ENV_VAR = "PATCHY_PATCHES_DIR";
export const PATCHY_REF_ENV_VAR = "PATCHY_REF";
export const PATCHY_CONFIG_ENV_VAR = "PATCHY_CONFIG";
export const PATCHY_VERBOSE_ENV_VAR = "PATCHY_VERBOSE";
export const PATCHY_DRY_RUN_ENV_VAR = "PATCHY_DRY_RUN";
